image:
  file: .docker/gitpod/Dockerfile

vscode:
  extensions:
    - leanprover.lean4

tasks:

  # These commands get entered because of clip-style chomping in the YAML processor
  - init: |
      lake exe cache get

    command: |

      # Append to .bashrc so that every new shell can find our source control scripts in the path
      # then exit this shell so the gitpod scripting will open a new shell, with the right path loaded
      echo -e "export PATH=${PATH}:/workspace/CS22-Lean-2023/scripts" >> ${HOME}/.bashrc && exit
