image:
  file: .docker/gitpod/Dockerfile

vscode:
  extensions:
    - leanprover.lean4

tasks:

  # These commands get entered because of clip-style chomping in the YAML processor
  - init: |
      lake exe cache get

    command: |

      # Append to .bashrc so that every new shell can find our source control scripts in the path
      # Ask user to close window so that path modification can take effect in new shell
      if [[ $PATH != *'/workspace/CS22-Lean-2023/scripts'* ]]; then 
          echo 'export PATH=${PATH}:/workspace/CS22-Lean-2023/scripts' >> ${HOME}/.bashrc
          echo
          echo
          echo "Please close all open terminals! They don't have the right environment variables :("
          echo 'You can do that by clicking the trashcan icon on all terminals displayed in the panel to the right.'
          echo 'A new, better terminal can be created in the `Terminal` submenu accessible under the settings bar in the top left,'
          echo 'or by pressing Ctrl-Shift-`'
      fi

