image:
  file: .docker/gitpod/Dockerfile

vscode:
  extensions:
    - leanprover.lean4

tasks:
  - init: |
      lake exe cache get
      curl https://cs.brown.edu/~rlewis13/save-to-firestore-0.13.1.vsix -o save-to-firestore-0.13.1.vsix
    command: |
      PATH="$PATH:/workspace/leanclass/scripts"

  
